### ISSUE TITLE
Upgrade to Flink 1.5

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/flink-crawler#140] opened 2018-04-25 19:18 UTC
It seems like the streaming test harness support only works properly with 1.5.

Ken also wants to take advantage of the broadcast stream merging for sending out ticklers so that we can do away with the artificially constructed keys we have to use now to put them into the keyed streams. 

For the moment we'll have to use 1.5-SNAPSHOT, but Ken has seen a few release candidates, so he thinks they're getting close.

**Comment by Schmed** [comment] 2018-04-25 21:09
I was able to get flink-crawler running locally on Flink 1.5. I updated the wiki instructions, but there were no source changes required (other than the pom.xml).

I'm going to re-assign this issue to @vmagotra so he can take a crack at running it in EMR (using the distribution I built from source and uploaded to S3 - see wiki instructions for running locally).

**Comment by Schmed** [comment] 2018-05-24 01:00
Ken sent me an email, which I plan to use to move from 1.5-SNAPSHOT to 1.5.0rc6:

Hi Schmed,

1. Add a repository to the pom

        <repository>
            <id>apache.flink.rc</id>
            <name>Apache Flink RC Repository</name>
            <url>https://repository.apache.org/content/repositories/orgapacheflink-1160/</url>
        </repository>

The “-1160” part of the url varies, depending on the release candidate. You can see all options at:

https://repository.apache.org/content/repositories/

Though this is for all Apache projects, so search for paths with “orgapacheflink-“.

2. Set the flink version property in the pom.xml to 1.5.0

		<flink.version>1.5.0</flink.version>

3. If you’re updating the repository to point to a new release candidate, you have to get rid of previously downloaded Flink 1.5.0 artifacts

Otherwise Maven thinks everything is OK, and won’t download the newer (or older) jars.

I did:

find ~/.m2/repository/org/apache/flink/ -name "1.5.0" | xargs rm -rf

— Ken

He also sent me the following via Slack:

Flink RC #5 artifacts are available at http://people.apache.org/~trohrmann/flink-1.5.0-rc5/

(you have to read the release candidate email to find out where they are located, as it’s up to the release manager)

**Comment by vmagotra** [comment] 2018-05-31 09:53
After updating to the release 1.5.0 version, I was able to run locally following the instructions on https://github.com/ScaleUnlimited/flink-crawler/wiki/Running-flink-crawler-locally.
I was also able to build ccdemo (branch 4_flink-1.5) and run locally.
However, when I tried to run ccdemo in EMR I got the following exception :  

	java.lang.NoClassDefFoundError: com/sun/jersey/core/util/FeaturesAndProperties
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
		at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at org.apache.hadoop.yarn.client.api.TimelineClient.createTimelineClient(TimelineClient.java:55)
		at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createTimelineClient(YarnClientImpl.java:181)
		at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceInit(YarnClientImpl.java:168)
		at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
		at org.apache.flink.yarn.cli.FlinkYarnSessionCli.getClusterDescriptor(FlinkYarnSessionCli.java:966)
		at org.apache.flink.yarn.cli.FlinkYarnSessionCli.createDescriptor(FlinkYarnSessionCli.java:269)
		at org.apache.flink.yarn.cli.FlinkYarnSessionCli.createClusterDescriptor(FlinkYarnSessionCli.java:444)
		at org.apache.flink.yarn.cli.FlinkYarnSessionCli.createClusterDescriptor(FlinkYarnSessionCli.java:92)
		at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:221)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:210)
		at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1020)
		at org.apache.flink.client.cli.CliFrontend.lambda$main$9(CliFrontend.java:1096)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
		at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1096)
	Caused by: java.lang.ClassNotFoundException: com.sun.jersey.core.util.FeaturesAndProperties
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 29 more


I see a question regarding this same issue here - http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/NoClassDefFoundError-for-jersey-core-on-YARN-td19214.html

I need to investigate further.

**Comment by vmagotra** [comment] 2018-06-07 00:10
The "fix" for this is the need to set up the hadoop classpath as per the release notes for Flink 1.5.0.

export HADOOP_CLASSPATH=`hadoop classpath`

**Comment by vmagotra** [comment] 2018-06-07 00:45
This has been merged into master - so closing this issue.

**Closed by vmagotra** 2018-06-07 00:45 UTC
